# Generated by Django 5.0.14 on 2026-05-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasteryRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("mastery_type", models.CharField(max_length=20)),
                ("target_code", models.CharField(max_length=64)),
                (
                    "mastery_status",
                    models.CharField(default="not_mastered", max_length=20),
                ),
                (
                    "mastery_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("next_review_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "mastery_record",
            },
        ),
        migrations.CreateModel(
            name="WrongBookItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_id", models.IntegerField()),
                ("first_wrong_at", models.DateTimeField(auto_now_add=True)),
                ("latest_wrong_at", models.DateTimeField(auto_now=True)),
                (
                    "wrong_reason_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("status", models.CharField(default="not_reviewed", max_length=20)),
                ("retry_count", models.IntegerField(default=0)),
                ("variant_done_count", models.IntegerField(default=0)),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "wrong_book_item",
                "unique_together": {("student_user_id", "question_id")},
            },
        ),
    ]
