# Generated by Django 5.2.16 on 2026-07-23 12:42
# 改为 RunSQL：integer→uuid 用 USING uuidv7()（Django 默认 cast 会失败）

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wrongbook", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE wrong_book_item ALTER COLUMN question_id TYPE uuid USING uuidv7();",
            reverse_sql="ALTER TABLE wrong_book_item ALTER COLUMN question_id TYPE integer USING NULL::integer;",
            state_operations=[
                migrations.AlterField("WrongBookItem", "question_id", models.UUIDField()),
            ],
        ),
    ]
