# Generated by Django 5.0.14 on 2026-05-30 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("class_no", models.CharField(blank=True, max_length=20, unique=True)),
                ("class_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("max_students", models.IntegerField(default=50)),
                (
                    "invite_code",
                    models.CharField(blank=True, max_length=8, unique=True),
                ),
                ("allow_invite_join", models.BooleanField(default=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator_teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="ClassJoinRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("applicant_name", models.CharField(max_length=100)),
                (
                    "applicant_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("request_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("message", models.TextField(blank=True, null=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="institutions.class",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_join_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_join_request",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("institution_name", models.CharField(max_length=200)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_institutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institution",
            },
        ),
        migrations.AddField(
            model_name="class",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="institutions.institution",
            ),
        ),
        migrations.CreateModel(
            name="ClassStudent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("join_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_students",
                        to="institutions.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_student",
                "unique_together": {("class_obj", "student")},
            },
        ),
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                (
                    "class_obj",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teachers",
                        to="institutions.class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_teacher",
                "unique_together": {("class_obj", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="InstitutionMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                ("status", models.CharField(default="active", max_length=20)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="institutions.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institution_member",
                "unique_together": {("institution", "user")},
            },
        ),
    ]
