# Generated by Django 5.2.16 on 2026-07-23 12:38

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_type", models.CharField(max_length=20)),
                ("login_name", models.CharField(blank=True, max_length=64, null=True)),
                ("mobile", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("subject", models.CharField(blank=True, max_length=20, null=True)),
                ("stages", models.JSONField(blank=True, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("grade_level", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_account",
            },
        ),
        migrations.CreateModel(
            name="StudentParentBind",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relation_type", models.CharField(max_length=20)),
                ("bind_status", models.CharField(default="pending", max_length=20)),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_binds_as_parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_binds_as_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_parent_bind",
            },
        ),
    ]
