# Generated by Django 5.0.14 on 2026-05-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_type", models.CharField(max_length=20)),
                ("login_name", models.CharField(blank=True, max_length=64, null=True)),
                ("mobile", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("avatar_url", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_account",
            },
        ),
        migrations.CreateModel(
            name="StudentParentBind",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("relation_type", models.CharField(max_length=20)),
                ("bind_status", models.CharField(default="pending", max_length=20)),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_binds_as_parent",
                        to="accounts.useraccount",
                    ),
                ),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_binds_as_student",
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "student_parent_bind",
            },
        ),
    ]
