# Generated by Django 5.2.16 on 2026-08-10 01:28

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WechatIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appid", models.CharField(max_length=64)),
                ("openid", models.CharField(max_length=128)),
                ("unionid", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wechat_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wechat_identity",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appid", "openid"), name="uq_wechat_appid_openid"
                    )
                ],
            },
        ),
    ]
