# Generated by Django 5.0.14 on 2026-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_useraccount_last_login_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="subject",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
