# Generated by Django 5.2.15 on 2026-08-13 03:30

import uuid

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


MIGRATABLE_ROLES = ("admin", "teacher", "parent", "student")
MIGRATION_SOURCE = "migration_0003"


def imported_grant_id(user_id, role):
    return uuid.uuid5(uuid.NAMESPACE_URL, f"accounts.UserRole:{user_id}:{role}")


def import_existing_role_grants(apps, schema_editor):
    UserAccount = apps.get_model("accounts", "UserAccount")
    StudentParentBind = apps.get_model("accounts", "StudentParentBind")
    UserRole = apps.get_model("accounts", "UserRole")

    role_pairs = {
        (user.id, role)
        for user in UserAccount.objects.exclude(role_type__isnull=True).iterator()
        if (role := user.role_type.strip()) in MIGRATABLE_ROLES
    }
    role_pairs.update(
        (bind.parent_user_id_id, "parent")
        for bind in StudentParentBind.objects.filter(bind_status="active").iterator()
    )
    role_pairs.update(
        (bind.student_user_id_id, "student")
        for bind in StudentParentBind.objects.filter(bind_status="active").iterator()
    )

    for user_id, role in sorted(role_pairs, key=lambda pair: (str(pair[0]), pair[1])):
        UserRole.objects.get_or_create(
            id=imported_grant_id(user_id, role),
            defaults={
                "user_id": user_id,
                "role": role,
                "status": "active",
                "grant_source": MIGRATION_SOURCE,
            },
        )


def remove_imported_role_grants(apps, schema_editor):
    UserRole = apps.get_model("accounts", "UserRole")
    imported_grant_ids = [
        grant.id
        for grant in UserRole.objects.filter(grant_source=MIGRATION_SOURCE)
        .only("id", "user_id", "role")
        .iterator()
        if grant.id == imported_grant_id(grant.user_id, grant.role)
    ]
    UserRole.objects.filter(
        id__in=imported_grant_ids, grant_source=MIGRATION_SOURCE
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_wechatidentity"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("teacher", "teacher"),
                            ("parent", "parent"),
                            ("student", "student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("grant_source", models.CharField(default="business", max_length=20)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_role",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"), name="uq_user_role_user_role"
                    )
                ],
            },
        ),
        migrations.RunPython(import_existing_role_grants, remove_imported_role_grants),
    ]
