# Generated by Django 5.2.16 on 2026-08-19

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="WechatWebIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appid", models.CharField(max_length=64)),
                ("openid", models.CharField(max_length=128)),
                ("unionid", models.CharField(blank=True, default="", max_length=128)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wechat_web_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wechat_web_identity",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("appid", "openid"),
                        name="uq_wechat_web_appid_openid",
                    )
                ],
            },
        ),
    ]
