# Generated by Django 5.0.14 on 2026-06-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_user_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="stages",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
