# Generated by Django 5.0.14 on 2026-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_useraccount_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="grade_level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
