# Generated by Django 5.0.14 on 2026-05-05 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_no", models.IntegerField(verbose_name="页码")),
                ("image_path", models.CharField(max_length=500, verbose_name="图片路径")),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="宽度"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="高度"),
                ),
                (
                    "ocr_text",
                    models.TextField(blank=True, null=True, verbose_name="OCR文本"),
                ),
                (
                    "layout_json",
                    models.JSONField(blank=True, null=True, verbose_name="布局JSON"),
                ),
                (
                    "parse_status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="解析状态"
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="AI置信度",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="papers.exampaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "试卷页面",
                "verbose_name_plural": "试卷页面",
                "db_table": "exam_page",
                "unique_together": {("paper", "page_no")},
            },
        ),
        migrations.CreateModel(
            name="AIParseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="qwen3-vl-plus", max_length=100, verbose_name="模型名称"
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Prompt版本"
                    ),
                ),
                (
                    "request_json",
                    models.JSONField(blank=True, null=True, verbose_name="请求JSON"),
                ),
                (
                    "response_json",
                    models.JSONField(blank=True, null=True, verbose_name="响应JSON"),
                ),
                (
                    "raw_response",
                    models.TextField(blank=True, null=True, verbose_name="原始响应"),
                ),
                (
                    "is_valid_json",
                    models.BooleanField(default=False, verbose_name="是否有效JSON"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "latency_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="延迟(毫秒)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_results",
                        to="papers.exampaper",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        db_column="page_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_results",
                        to="parser.exampage",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI解析结果",
                "verbose_name_plural": "AI解析结果",
                "db_table": "ai_parse_result",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_no", models.CharField(max_length=50, verbose_name="题号")),
                (
                    "section_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="大题标题"
                    ),
                ),
                ("question_type", models.CharField(max_length=50, verbose_name="题型")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学科"
                    ),
                ),
                ("stem", models.TextField(verbose_name="题干")),
                (
                    "stem_html",
                    models.TextField(blank=True, null=True, verbose_name="题干HTML"),
                ),
                ("answer", models.TextField(blank=True, null=True, verbose_name="答案")),
                (
                    "analysis",
                    models.TextField(blank=True, null=True, verbose_name="解析"),
                ),
                (
                    "solution",
                    models.TextField(blank=True, null=True, verbose_name="详解"),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="点评")),
                (
                    "raw_explanation",
                    models.TextField(blank=True, null=True, verbose_name="原始解释"),
                ),
                (
                    "raw_text",
                    models.TextField(blank=True, null=True, verbose_name="原始文本"),
                ),
                (
                    "knowledge_points",
                    models.JSONField(blank=True, null=True, verbose_name="知识点"),
                ),
                (
                    "difficulty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="难度",
                    ),
                ),
                (
                    "page_start",
                    models.IntegerField(blank=True, null=True, verbose_name="起始页"),
                ),
                (
                    "page_end",
                    models.IntegerField(blank=True, null=True, verbose_name="结束页"),
                ),
                (
                    "bbox",
                    models.JSONField(blank=True, null=True, verbose_name="主区域bbox"),
                ),
                (
                    "region_json",
                    models.JSONField(blank=True, null=True, verbose_name="跨页区域"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        verbose_name="置信度",
                    ),
                ),
                (
                    "formula_need_review",
                    models.BooleanField(default=False, verbose_name="公式需复核"),
                ),
                (
                    "need_review",
                    models.BooleanField(default=True, verbose_name="需人工校验"),
                ),
                (
                    "review_status",
                    models.CharField(
                        default="unreviewed", max_length=50, verbose_name="复核状态"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        default="auto_parsed", max_length=50, verbose_name="解析状态"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_question",
                    models.ForeignKey(
                        blank=True,
                        db_column="original_question_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_versions",
                        to="parser.examquestion",
                        verbose_name="原始题目",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="papers.exampaper",
                    ),
                ),
                (
                    "parent_question",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_question_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_questions",
                        to="parser.examquestion",
                        verbose_name="父题",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "exam_question",
            },
        ),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        default="other", max_length=50, verbose_name="图片类型"
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                (
                    "source_page_image_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="源页面图路径"
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(blank=True, null=True, verbose_name="原始bbox"),
                ),
                (
                    "expanded_bbox",
                    models.JSONField(blank=True, null=True, verbose_name="扩边bbox"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="描述"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        db_column="page_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_images",
                        to="parser.exampage",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_images",
                        to="papers.exampaper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="parser.examquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目插图",
                "verbose_name_plural": "题目插图",
                "db_table": "question_image",
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_label", models.CharField(max_length=10, verbose_name="选项标签")),
                ("content", models.TextField(verbose_name="选项内容")),
                (
                    "content_html",
                    models.TextField(blank=True, null=True, verbose_name="选项HTML"),
                ),
                ("bbox", models.JSONField(blank=True, null=True, verbose_name="bbox")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="parser.examquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
                "db_table": "question_option",
            },
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(
                fields=["paper", "question_no"], name="idx_paper_question"
            ),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(fields=["question_type"], name="idx_question_type"),
        ),
        migrations.AddIndex(
            model_name="examquestion",
            index=models.Index(fields=["review_status"], name="idx_review_status"),
        ),
        migrations.AlterUniqueTogether(
            name="questionoption",
            unique_together={("question", "option_label")},
        ),
    ]
