# Generated by Django 5.0.14 on 2026-05-05 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="aiparseresult",
            table="tiku_ai_parse_result",
        ),
        migrations.AlterModelTable(
            name="exampage",
            table="tiku_exam_page",
        ),
        migrations.AlterModelTable(
            name="examquestion",
            table="tiku_exam_question",
        ),
        migrations.AlterModelTable(
            name="questionimage",
            table="tiku_question_image",
        ),
        migrations.AlterModelTable(
            name="questionoption",
            table="tiku_question_option",
        ),
    ]
