# Generated by Django 5.2.15 on 2026-07-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="用于生成条形码的编码值，通常等于system_id",
                max_length=100,
                null=True,
                verbose_name="条形码数据",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="collected_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="收录日期"),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="creator_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="创建者姓名"
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="source_collection",
            field=models.CharField(
                blank=True,
                help_text="如: 物理小题狂做试卷",
                max_length=255,
                null=True,
                verbose_name="来源题集",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='如: ["期末提优", "易错题", "压轴题"]',
                null=True,
                verbose_name="自定义标签",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="video_explanation_url",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="视频解析URL"
            ),
        ),
    ]
