# Generated by Django 5.0.14 on 2026-05-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0005_add_ai_answer_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestion",
            name="ai_answer_a",
            field=models.JSONField(blank=True, null=True, verbose_name="AI答案A模式"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="ai_answer_b",
            field=models.JSONField(blank=True, null=True, verbose_name="AI答案B模式"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="ai_answer_c",
            field=models.JSONField(blank=True, null=True, verbose_name="AI答案C模式"),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="ai_knowledge_enrichment",
            field=models.JSONField(blank=True, null=True, verbose_name="AI知识点 enrich"),
        ),
    ]
