# Generated by Django 5.2.15 on 2026-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0007_examquestion_json_source_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L1", "L1"),
                    ("L2", "L2"),
                    ("L3", "L3"),
                    ("L4", "L4"),
                    ("L5", "L5"),
                ],
                help_text=(
                    "AI 探查的粗粒度难度等级，和具体难度数值 difficulty "
                    "分开保存。"
                ),
                max_length=2,
                null=True,
                verbose_name="难度等级",
            ),
        ),
    ]
