# Generated by Django 5.2.16 on 2026-09-05

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_controlled_probe_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionContentFingerprint',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                (
                    'algorithm_version',
                    models.CharField(default='content-v1', max_length=32),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[('reserving', 'Reserving'), ('active', 'Active')],
                        default='reserving',
                        max_length=16,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'canonical_question',
                    models.OneToOneField(
                        blank=True,
                        db_column='canonical_question_id',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='content_fingerprint',
                        to='parser.examquestion',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Question content fingerprint',
                'verbose_name_plural': 'Question content fingerprints',
                'db_table': 'tiku_question_content_fingerprint',
            },
        ),
    ]
