# Generated by Django 5.2.16 on 2026-09-05

import apps.parser.question_identity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0009_question_content_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncontentfingerprint',
            name='fingerprint',
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[apps.parser.question_identity.validate_content_fingerprint],
            ),
        ),
        migrations.AddConstraint(
            model_name='questioncontentfingerprint',
            constraint=models.CheckConstraint(
                condition=models.Q(('fingerprint__regex', '^[0-9a-f]{64}$')),
                name='qcf_fingerprint_lower_sha256',
            ),
        ),
    ]
