# Generated by Django 5.2.16 on 2026-09-16 10:08

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0006_studentimportrow_target_class"),
        ("missions", "0022_classroomwrongdrillitem_relation_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassroomFeedbackReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_matrix_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "生成中"),
                            ("ready", "已完成"),
                            ("partial", "部分完成"),
                            ("failed", "失败"),
                            ("stale", "数据已更新"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("generation_no", models.PositiveIntegerField(default=1)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("total_wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "average_wrong_count",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("class_summary_json", models.JSONField(blank=True, default=dict)),
                ("class_feedback_text", models.TextField(blank=True, default="")),
                ("input_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "prompt_version",
                    models.CharField(default="classroom-feedback-v1", max_length=50),
                ),
                (
                    "model_name",
                    models.CharField(default="qwen3.7-flash", max_length=100),
                ),
                (
                    "pdf_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_feedback_reports",
                        to="institutions.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classroom_feedback_reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_feedback_reports",
                        to="missions.learningmission",
                    ),
                ),
                (
                    "source_matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classroom_feedback_reports",
                        to="missions.teacherwrongbookmatrix",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_feedback_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomFeedbackQuestionStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_question_id", models.UUIDField()),
                ("node_id", models.UUIDField(blank=True, null=True)),
                (
                    "node_name_snapshot",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("node_sort_no", models.PositiveIntegerField(default=0)),
                (
                    "question_no",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "wrong_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("knowledge_labels", models.JSONField(blank=True, default=list)),
                ("question_snapshot", models.JSONField(blank=True, default=dict)),
                ("sort_no", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_stats",
                        to="classroom_feedback.classroomfeedbackreport",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_feedback_question_stat",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomFeedbackKnowledgeStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("knowledge_key", models.CharField(max_length=120)),
                ("knowledge_name", models.CharField(max_length=255)),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                ("denominator", models.PositiveIntegerField(default=0)),
                (
                    "error_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("mastery_level", models.CharField(default="attention", max_length=30)),
                ("question_ids", models.JSONField(blank=True, default=list)),
                ("sort_no", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_stats",
                        to="classroom_feedback.classroomfeedbackreport",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_feedback_knowledge_stat",
                "ordering": ["sort_no", "knowledge_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomFeedbackStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_name_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "class_name_snapshot",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "student_no_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("wrong_question_ids", models.JSONField(blank=True, default=list)),
                ("wrong_question_nos", models.JSONField(blank=True, default=list)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                (
                    "wrong_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("knowledge_summary", models.JSONField(blank=True, default=list)),
                ("review_arrangement", models.JSONField(blank=True, default=list)),
                ("feedback_text", models.TextField(blank=True, default="")),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("pending", "待生成"),
                            ("succeeded", "已生成"),
                            ("fallback", "规则兜底"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_model", models.CharField(default="qwen3.7-flash", max_length=100)),
                (
                    "prompt_version",
                    models.CharField(default="classroom-feedback-v1", max_length=50),
                ),
                (
                    "ai_input_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "ai_error_message",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_feedbacks",
                        to="classroom_feedback.classroomfeedbackreport",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classroom_feedback_rows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classroom_feedback_student",
                "ordering": ["student_name_snapshot", "student_no_snapshot", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="classroomfeedbackreport",
            index=models.Index(
                fields=["mission", "class_obj", "-created_at"],
                name="cf_report_mission_class_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classroomfeedbackreport",
            index=models.Index(
                fields=["source_matrix", "source_matrix_version"],
                name="cf_report_matrix_ver_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomfeedbackquestionstat",
            constraint=models.UniqueConstraint(
                fields=("report", "source_question_id"),
                name="cf_question_report_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomfeedbackknowledgestat",
            constraint=models.UniqueConstraint(
                fields=("report", "knowledge_key"),
                name="cf_knowledge_report_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomfeedbackstudent",
            constraint=models.UniqueConstraint(
                fields=("report", "student"), name="cf_student_report_student_unique"
            ),
        ),
    ]
