# Generated by Django 5.2.16 on 2026-08-10 01:28

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        ("missions", "0005_missionquestionrel_target_students"),
        ("study", "0004_answerattempt_image_count"),
        ("wrongbook", "0002_alter_wrongbookitem_question_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperScanBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="scanning", max_length=20)),
                ("expected_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_scan_batches",
                        to="missions.learningmission",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_scan_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_scan_batch",
            },
        ),
        migrations.CreateModel(
            name="WrongbookPracticeSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sheet_code",
                    models.CharField(db_index=True, max_length=6, unique=True),
                ),
                ("original_question_id", models.UUIDField()),
                ("variant_question_ids", models.JSONField(blank=True, default=list)),
                ("wrong_reason_hint", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "submit_source",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        db_column="class_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="institutions.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wrong_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sheets",
                        to="wrongbook.wrongbookitem",
                    ),
                ),
            ],
            options={
                "db_table": "wrongbook_practice_sheet",
            },
        ),
        migrations.CreateModel(
            name="AttemptImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.UUIDField()),
                ("image_url", models.CharField(max_length=1000)),
                ("page_no", models.IntegerField(default=1)),
                (
                    "blur_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_blurry", models.BooleanField(default=False)),
                ("upload_status", models.CharField(default="completed", max_length=20)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="study.answerattempt",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attempt_image",
                "ordering": ["page_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "page_no"),
                        name="uq_attempt_image_attempt_page",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MissionShortCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(db_index=True, max_length=6, unique=True),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="active", max_length=20)),
                ("scan_count", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        db_column="class_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="institutions.class",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_codes",
                        to="missions.learningmission",
                    ),
                ),
            ],
            options={
                "db_table": "mission_short_code",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "class_obj"),
                        name="uq_mission_short_code_mission_class",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperScanPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_code", models.CharField(max_length=8)),
                ("mission_code", models.CharField(max_length=6)),
                ("page_no", models.PositiveIntegerField()),
                ("total_pages", models.PositiveIntegerField(default=1)),
                ("image_url", models.CharField(max_length=1000)),
                ("status", models.CharField(default="uploaded", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="qrcode.paperscanbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_scan_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_scan_page",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "student", "page_no"),
                        name="uq_paper_scan_batch_student_page",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentClassShortCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_code",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_short_codes",
                        to="institutions.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_short_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_class_short_code",
                "unique_together": {("student", "class_obj")},
            },
        ),
    ]
