# Generated by Django 5.2.15 on 2026-08-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperscanpage",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="paperscanpage",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="wrongbookpracticesheet",
            name="answers_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="wrongbookpracticesheet",
            name="mode",
            field=models.CharField(default="online", max_length=20),
        ),
        migrations.AddField(
            model_name="wrongbookpracticesheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
