# Generated by Django 5.0.14 on 2026-07-14 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("parser", "0007_add_ai_processing_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="课程名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="课程描述"),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="学科")),
                ("grade_level", models.CharField(max_length=50, verbose_name="年级")),
                (
                    "cover_image",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="封面图片"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="软删除标记"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        db_column="teacher_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="资料名称")),
                ("file_path", models.CharField(max_length=500, verbose_name="文件路径")),
                ("file_type", models.CharField(max_length=20, verbose_name="文件类型")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小(字节)")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME类型")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="软删除标记"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程资料",
                "verbose_name_plural": "课程资料",
                "db_table": "course_material",
            },
        ),
        migrations.CreateModel(
            name="CourseTree",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="节点名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tree_nodes",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="courses.coursetree",
                        verbose_name="父节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程树节点",
                "verbose_name_plural": "课程树节点",
                "db_table": "course_tree",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="VariantTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("variant_mode", models.CharField(max_length=30, verbose_name="变式模式")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "处理中"),
                            ("success", "处理成功"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "generator_result",
                    models.JSONField(blank=True, null=True, verbose_name="生成器结果"),
                ),
                (
                    "verifier_result",
                    models.JSONField(blank=True, null=True, verbose_name="校验器结果"),
                ),
                (
                    "generated_question",
                    models.JSONField(blank=True, null=True, verbose_name="生成的题目"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "original_question",
                    models.ForeignKey(
                        db_column="original_question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_tasks",
                        to="parser.examquestion",
                        verbose_name="原始题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "变式题任务",
                "verbose_name_plural": "变式题任务",
                "db_table": "course_variant_task",
            },
        ),
        migrations.CreateModel(
            name="CourseQuestionLink",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "手动添加"),
                            ("import", "导入"),
                            ("generated", "生成"),
                        ],
                        max_length=30,
                        verbose_name="来源",
                    ),
                ),
                (
                    "source_course_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="源课程名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="软删除标记"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_links",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_links",
                        to="parser.examquestion",
                        verbose_name="习题",
                    ),
                ),
                (
                    "tree_node",
                    models.ForeignKey(
                        blank=True,
                        db_column="tree_node_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_links",
                        to="courses.coursetree",
                        verbose_name="树节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程习题关联",
                "verbose_name_plural": "课程习题关联",
                "db_table": "course_question_link",
                "unique_together": {("course", "question")},
            },
        ),
    ]
