# Generated by Django 5.2.16 on 2026-07-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursequestionlink",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_links",
                to="parser.examquestion",
                verbose_name="习题",
            ),
        ),
        migrations.AddField(
            model_name="coursetree",
            name="course",
            field=models.ForeignKey(
                db_column="course_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tree_nodes",
                to="courses.course",
                verbose_name="课程",
            ),
        ),
        migrations.AddField(
            model_name="coursetree",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="courses.coursetree",
                verbose_name="父节点",
            ),
        ),
        migrations.AddField(
            model_name="coursequestionlink",
            name="tree_node",
            field=models.ForeignKey(
                blank=True,
                db_column="tree_node_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_links",
                to="courses.coursetree",
                verbose_name="树节点",
            ),
        ),
        migrations.AddField(
            model_name="varianttask",
            name="original_question",
            field=models.ForeignKey(
                db_column="original_question_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_tasks",
                to="parser.examquestion",
                verbose_name="原始题目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursequestionlink",
            unique_together={("course", "question")},
        ),
    ]
