# Generated by Django 5.2.16 on 2026-08-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_scope_collaboration"),
        ("institutions", "0004_class_grade_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_obj",
                    models.ForeignKey(
                        db_column="class_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_relations",
                        to="institutions.class",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_relations",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_class",
            },
        ),
        migrations.CreateModel(
            name="CourseHandout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_no", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handout_relations",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_handout",
            },
        ),
    ]
