# Generated by Django 5.2.15 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_scope_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='conversion_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='转换完成时间'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='conversion_error',
            field=models.TextField(blank=True, null=True, verbose_name='格式转换错误'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='conversion_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='转换开始时间'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='conversion_status',
            field=models.CharField(choices=[('not_required', '无需转换'), ('pending', '等待转换'), ('converting', '格式转换中'), ('completed', '格式转换完成'), ('failed', '格式转换失败')], db_index=True, default='not_required', max_length=20, verbose_name='格式转换状态'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='converted_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='转换后 PDF 路径'),
        ),
    ]
