# Generated by Django 5.2.16 on 2026-08-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_courseclass_coursehandout"),
        ("handouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursehandout",
            name="handout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_relations",
                to="handouts.handout",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseclass",
            constraint=models.UniqueConstraint(
                fields=("course", "class_obj"), name="uq_course_class"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursehandout",
            constraint=models.UniqueConstraint(
                fields=("course", "handout"), name="uq_course_handout"
            ),
        ),
    ]
