# Generated by Django 5.0.14 on 2026-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "数学"), ("physics", "物理")], max_length=50
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[("primary", "小学"), ("junior", "初中"), ("senior", "高中")],
                        max_length=20,
                    ),
                ),
                ("grade_index", models.PositiveSmallIntegerField()),
                ("grade_name", models.CharField(max_length=20)),
                (
                    "term",
                    models.CharField(
                        choices=[("up", "上学期"), ("down", "下学期")], max_length=10
                    ),
                ),
                ("chapter", models.CharField(max_length=255)),
                ("module", models.CharField(max_length=255)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("formula", "公式"),
                            ("property", "属性"),
                            ("method", "方法"),
                            ("type", "类型"),
                            ("general", "通用"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "知识点",
                "verbose_name_plural": "知识点",
                "db_table": "knowledge_points",
                "managed": False,
            },
        ),
    ]
