# Generated by Django 5.2.15 on 2026-08-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeTopic",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=120, primary_key=True, serialize=False
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[("math", "数学"), ("physics", "物理")],
                        max_length=50,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("primary", "小学"),
                            ("junior", "初中"),
                            ("senior", "高中"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("catalog_version", models.CharField(default="v1", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge.knowledgetopic",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_controlled_topic",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTopicModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_links",
                        to="knowledge.knowledgetopic",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_controlled_topic_module",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="knowledgetopic",
            index=models.Index(
                fields=["subject", "stage", "parent", "is_enabled"],
                name="knowledge_topic_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgetopicmodule",
            index=models.Index(
                fields=["module", "is_enabled"],
                name="kn_topic_module_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgetopicmodule",
            constraint=models.UniqueConstraint(
                fields=("topic", "module"),
                name="knowledge_topic_module_unique",
            ),
        ),
    ]
