# Generated by Django 5.2.16 on 2026-08-28 07:49

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0002_controlled_probe_taxonomy"),
        ("parser", "0007_examquestion_json_source_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionKnowledgeMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "manual"),
                            ("import", "import"),
                            ("rule", "rule"),
                            ("ai", "ai"),
                        ],
                        default="rule",
                        max_length=20,
                    ),
                ),
                ("source_version", models.CharField(default="rule-v1", max_length=30)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "suggested"),
                            ("confirmed", "confirmed"),
                            ("rejected", "rejected"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                ("evidence", models.JSONField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_question_knowledge_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        blank=True,
                        db_column="knowledge_point_id",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_matches",
                        to="knowledge.knowledgepoint",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_matches",
                        to="parser.examquestion",
                    ),
                ),
            ],
            options={
                "db_table": "question_knowledge_match",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "knowledge_point", "source_version"),
                        name="uq_question_kp_match_version",
                    )
                ],
            },
        ),
    ]
