# Generated by Django 5.0.14 on 2026-05-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGuidanceSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_id", models.IntegerField()),
                ("mode_type", models.CharField(max_length=10)),
                ("session_status", models.CharField(default="running", max_length=20)),
                ("invalid_input_count", models.IntegerField(default=0)),
                (
                    "script_source",
                    models.CharField(default="ai_generated", max_length=20),
                ),
                ("content_log_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "ai_guidance_session",
            },
        ),
        migrations.CreateModel(
            name="AnswerAttempt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_id", models.IntegerField()),
                ("attempt_no", models.IntegerField(default=1)),
                ("answer_content", models.JSONField(default=dict)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("submit_source", models.CharField(default="manual", max_length=20)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.missionlevel",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.learningmission",
                    ),
                ),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "answer_attempt",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentLevelProgress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="locked", max_length=20)),
                (
                    "pass_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("passed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.missionlevel",
                    ),
                ),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "student_level_progress",
                "unique_together": {("level", "student_user_id")},
            },
        ),
        migrations.CreateModel(
            name="StudentMissionProgress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "progress_status",
                    models.CharField(default="not_started", max_length=20),
                ),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("last_action_at", models.DateTimeField(auto_now=True)),
                (
                    "current_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="missions.missionlevel",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.learningmission",
                    ),
                ),
                (
                    "student_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "student_mission_progress",
                "unique_together": {("mission", "student_user_id")},
            },
        ),
    ]
