# Generated by Django 5.2.15 on 2026-07-28 01:23

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0002_examquestion_barcode_data_examquestion_collected_at_and_more"),
        ("study", "0002_alter_aiguidancesession_question_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="标签名称"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409eff", max_length=20, verbose_name="标签颜色"
                    ),
                ),
                ("question_count", models.IntegerField(default=0, verbose_name="题目数量")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目标签",
                "verbose_name_plural": "题目标签",
                "db_table": "tiku_question_tag",
                "ordering": ["-question_count"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBasket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.UUIDField(db_index=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "题目篮子",
                "verbose_name_plural": "题目篮子",
                "db_table": "tiku_question_basket",
                "ordering": ["-added_at"],
                "unique_together": {("user", "question_id")},
            },
        ),
        migrations.CreateModel(
            name="QuestionTagRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parser.examquestion",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study.questiontag",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目标签关联",
                "verbose_name_plural": "题目标签关联",
                "db_table": "tiku_question_tag_relation",
                "unique_together": {("question", "tag")},
            },
        ),
    ]
