# Generated by Django 5.2.15 on 2026-07-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerattempt",
            name="is_subjective_pending",
            field=models.BooleanField(default=False),
        ),
    ]
