# Generated by Django 5.2.16 on 2026-08-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0003_questiontag_questionbasket_questiontagrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerattempt",
            name="image_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
