# Generated by Django 5.2.15 on 2026-08-30 05:32

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_controlled_probe_taxonomy'),
        ('study', '0004_answerattempt_image_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRelation',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_relations', to='parser.examquestion')),
                ('question_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_relations', to='parser.examquestion')),
            ],
            options={
                'db_table': 'tiku_question_relation',
                'constraints': [models.UniqueConstraint(fields=('question_left', 'question_right'), name='uq_question_relation_pair')],
            },
        ),
    ]
