# Generated by Django 5.2.16 on 2026-09-05

import django.db.models.deletion
import django.utils.timezone
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_remote_material_status_and_local_course_relations'),
        ('papers', '0003_exam_paper_source_fields'),
        ('study', '0006_merge_questionrelation_and_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('json_import', 'JSON import'), ('manual_create', 'Manual create'), ('photo_create', 'Photo create'), ('course_material_import', 'Course material import'), ('course_link_import', 'Course link import')], max_length=32)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('total_read', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_existing_count', models.PositiveIntegerField(default=0)),
                ('skipped_in_package_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ingestion_batches', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_ingestion_batches', to='courses.course')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_ingestion_batches', to='papers.exampaper')),
            ],
            options={
                'db_table': 'question_ingestion_batch',
                'ordering': ['-finished_at', '-created_at'],
            },
        ),
    ]
