# Generated by Django 5.2.15 on 2026-09-13 10:57

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_merge_remote_material_status_and_local_course_relations'),
        ('study', '0007_question_ingestion_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioningestionbatch',
            name='source_type',
            field=models.CharField(choices=[('json_import', 'JSON import'), ('manual_create', 'Manual create'), ('photo_create', 'Photo create'), ('course_material_import', 'Course material import'), ('course_link_import', 'Course link import'), ('document_import', 'Document import')], max_length=32),
        ),
        migrations.CreateModel(
            name='QuestionDocumentImportTask',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=500)),
                ('detected_mime', models.CharField(max_length=127)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('page_count', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('structuring', 'Structuring'), ('importing', 'Importing'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('linked_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_import_task', to='study.questioningestionbatch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_import_tasks', to='courses.course')),
            ],
            options={
                'db_table': 'question_document_import_task',
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='ck_document_import_progress_100')],
            },
        ),
    ]
