# Generated by Django 5.2.15 on 2026-09-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0006_merge_remote_material_status_and_local_course_relations'),
        ('study', '0008_questiondocumentimporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='tree_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='document_import_tasks', to='courses.coursetree'),
        ),
    ]
