# Generated by Django 5.2.16 on 2026-09-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0009_questiondocumentimporttask_tree_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiondocumentimporttask",
            name="import_purpose",
            field=models.CharField(default="document_import", max_length=40),
        ),
        migrations.AddField(
            model_name="questiondocumentimporttask",
            name="source_type",
            field=models.CharField(default="document_import", max_length=40),
        ),
        migrations.AddField(
            model_name="questiondocumentimporttask",
            name="wrong_drill_source_set_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="questioningestionbatch",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("json_import", "JSON import"),
                    ("manual_create", "Manual create"),
                    ("photo_create", "Photo create"),
                    ("course_material_import", "Course material import"),
                    ("course_link_import", "Course link import"),
                    ("document_import", "Document import"),
                    ("wrongbook_drill", "Wrongbook drill source"),
                ],
                max_length=32,
            ),
        ),
    ]
