# Generated by Django 5.2.16 on 2026-09-16

import uuid_utils.compat
from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):
    dependencies = [
        ('study', '0010_questiondocumentimporttask_import_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='document_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='failed_question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiondocumentimporttask',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionDocumentImportItem',
            fields=[
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_position', models.PositiveIntegerField()),
                ('question_no', models.CharField(blank=True, default='', max_length=100)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('candidate_json', models.JSONField(default=dict)),
                ('asset_files_json', models.JSONField(default=dict)),
                ('prompt_version', models.CharField(default='document_structure:v1', max_length=64)),
                ('model_name', models.CharField(default='qwen3.7-plus', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=16)),
                ('ingest_status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('ingested', 'Ingested'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('structured_result_json', models.JSONField(blank=True, null=True)),
                ('ingest_result_json', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message_safe', models.CharField(blank=True, default='', max_length=500)),
                ('ingest_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('ingest_error_message_safe', models.CharField(blank=True, default='', max_length=500)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_import_task', models.ForeignKey(on_delete=CASCADE, related_name='items', to='study.questiondocumentimporttask')),
            ],
            options={
                'db_table': 'question_document_import_item',
                'indexes': [
                    models.Index(fields=['document_import_task', 'status'], name='question_do_documen_7a6c0a_idx'),
                    models.Index(fields=['document_import_task', 'ingest_status'], name='question_do_documen_5df9c3_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('document_import_task', 'source_position'), name='uq_document_import_item_task_position'),
                ],
            },
        ),
    ]
