-- ============================================================
-- 表名: answer_attempt
-- 说明: 学生答题记录表，记录每次答题的详细信息
-- 创建日期: 2026-07-10
-- 数据库: PostgreSQL
-- ============================================================

-- 1. 建表（含主键）
CREATE TABLE answer_attempt (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    student_user_id_id BIGINT NOT NULL,
    mission_id BIGINT NULL,
    level_id BIGINT NULL,
    question_id INTEGER NOT NULL,
    attempt_no INTEGER NOT NULL,
    answer_content JSONB NOT NULL,
    is_correct BOOLEAN NOT NULL,
    is_subjective_pending BOOLEAN NOT NULL,
    score NUMERIC(5, 2) NOT NULL,
    submit_source VARCHAR(20) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT answer_attempt_pkey PRIMARY KEY (id)
);

-- 2. 字段注释
COMMENT ON TABLE answer_attempt IS '学生答题记录';
COMMENT ON COLUMN answer_attempt.id IS '主键ID';
COMMENT ON COLUMN answer_attempt.student_user_id_id IS '学生用户ID，关联 user_account(id)';
COMMENT ON COLUMN answer_attempt.mission_id IS '学习任务ID，关联 learning_mission(id)';
COMMENT ON COLUMN answer_attempt.level_id IS '任务关卡ID，关联 mission_level(id)';
COMMENT ON COLUMN answer_attempt.question_id IS '题目ID';
COMMENT ON COLUMN answer_attempt.attempt_no IS '第几次作答（默认1）';
COMMENT ON COLUMN answer_attempt.answer_content IS '作答内容（JSON格式）';
COMMENT ON COLUMN answer_attempt.is_correct IS '是否正确';
COMMENT ON COLUMN answer_attempt.is_subjective_pending IS '主观题待批阅标记';
COMMENT ON COLUMN answer_attempt.score IS '得分（满分5位，小数2位）';
COMMENT ON COLUMN answer_attempt.submit_source IS '提交来源（默认 manual）';
COMMENT ON COLUMN answer_attempt.submitted_at IS '提交时间';

-- 3. 外键约束
ALTER TABLE answer_attempt
    ADD CONSTRAINT answer_attempt_student_user_id_id_fk
    FOREIGN KEY (student_user_id_id) REFERENCES user_account(id)
    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE answer_attempt
    ADD CONSTRAINT answer_attempt_mission_id_fk
    FOREIGN KEY (mission_id) REFERENCES learning_mission(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE answer_attempt
    ADD CONSTRAINT answer_attempt_level_id_fk
    FOREIGN KEY (level_id) REFERENCES mission_level(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

-- 4. 索引（外键索引 + 排序优化）
CREATE INDEX answer_attempt_student_user_id_id_idx
    ON answer_attempt(student_user_id_id);
CREATE INDEX answer_attempt_mission_id_idx
    ON answer_attempt(mission_id);
CREATE INDEX answer_attempt_level_id_idx
    ON answer_attempt(level_id);
CREATE INDEX answer_attempt_submitted_at_desc_idx
    ON answer_attempt(submitted_at DESC);

-- ============================================================
-- 可选：如果需要在数据库层面设置默认值（Django ORM 默认在应用层处理）
-- ============================================================
-- ALTER TABLE answer_attempt ALTER COLUMN attempt_no SET DEFAULT 1;
-- ALTER TABLE answer_attempt ALTER COLUMN answer_content SET DEFAULT '{}';
-- ALTER TABLE answer_attempt ALTER COLUMN is_correct SET DEFAULT false;
-- ALTER TABLE answer_attempt ALTER COLUMN is_subjective_pending SET DEFAULT false;
-- ALTER TABLE answer_attempt ALTER COLUMN score SET DEFAULT 0.00;
-- ALTER TABLE answer_attempt ALTER COLUMN submit_source SET DEFAULT 'manual';