# Generated by Django 5.2.16 on 2026-08-21 02:31

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wrongbook", "0002_alter_wrongbookitem_question_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticePoolItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.UUIDField(db_index=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("original_wrong", "原错题"),
                            ("recommended_variant", "关联题"),
                            ("manual", "手工题"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recommendation_snapshot", models.JSONField(blank=True, null=True)),
                ("display_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("removed", "已移除")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_wrong_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="source_wrong_item_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practice_pool_items",
                        to="wrongbook.wrongbookitem",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_pool_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practice_pool_item",
            },
        ),
        migrations.CreateModel(
            name="PracticeSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_via_role",
                    models.CharField(
                        choices=[("student", "学生"), ("parent", "家长")], max_length=20
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "练习中"),
                            ("completed", "已完成"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("answered_count", models.PositiveIntegerField(default=0)),
                (
                    "progress_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pdf_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("pdf_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        db_column="created_by_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_practice_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practice_set",
            },
        ),
        migrations.CreateModel(
            name="PracticeSetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_id", models.UUIDField()),
                ("sort_no", models.PositiveIntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("original_wrong", "原错题"),
                            ("recommended_variant", "关联题"),
                            ("manual", "手工题"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pool_item",
                    models.ForeignKey(
                        blank=True,
                        db_column="pool_item_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="set_items",
                        to="practice.practicepoolitem",
                    ),
                ),
                (
                    "practice_set",
                    models.ForeignKey(
                        db_column="practice_set_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="practice.practiceset",
                    ),
                ),
            ],
            options={
                "db_table": "practice_set_item",
            },
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_content", models.JSONField(default=dict)),
                (
                    "submit_source",
                    models.CharField(
                        choices=[("online", "在线"), ("photo", "照片"), ("paper", "纸笔")],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("attempt_no", models.PositiveIntegerField(default=1)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("is_subjective_pending", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("pending_review", "待批阅"),
                            ("graded", "已批阅"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_user",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "practice_set",
                    models.ForeignKey(
                        db_column="practice_set_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="practice.practiceset",
                    ),
                ),
                (
                    "set_item",
                    models.ForeignKey(
                        db_column="set_item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="practice.practicesetitem",
                    ),
                ),
            ],
            options={
                "db_table": "practice_attempt",
            },
        ),
        migrations.CreateModel(
            name="PracticeAttemptImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(max_length=1000)),
                ("page_no", models.PositiveIntegerField()),
                (
                    "blur_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_blurry", models.BooleanField(default=False)),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        db_column="attempt_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="practice.practiceattempt",
                    ),
                ),
                (
                    "student_user",
                    models.ForeignKey(
                        db_column="student_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_attempt_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "practice_attempt_image",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "page_no"),
                        name="uq_practice_attempt_image_page",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="practicepoolitem",
            index=models.Index(
                fields=["student_user", "status", "created_at"],
                name="ix_pp_stu_st_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicepoolitem",
            constraint=models.UniqueConstraint(
                fields=("student_user", "question_id"),
                name="uq_practice_pool_student_question",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceset",
            index=models.Index(
                fields=["student_user", "status", "updated_at"],
                name="ix_ps_stu_st_updated",
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesetitem",
            constraint=models.UniqueConstraint(
                fields=("practice_set", "sort_no"), name="uq_practice_set_sort_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicesetitem",
            constraint=models.UniqueConstraint(
                fields=("practice_set", "question_id"), name="uq_practice_set_question"
            ),
        ),
        migrations.AddIndex(
            model_name="practiceattempt",
            index=models.Index(
                fields=["practice_set", "set_item"],
                name="idx_practice_attempt_set_item",
            ),
        ),
        migrations.AddIndex(
            model_name="practiceattempt",
            index=models.Index(
                fields=["student_user", "status"], name="ix_pa_stu_status"
            ),
        ),
    ]
