# Generated by Django 5.0.14 on 2026-05-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "mission_no",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("mission_name", models.CharField(max_length=120)),
                ("goal_text", models.CharField(blank=True, default="", max_length=255)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "default_mode_policy",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator_teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "learning_mission",
            },
        ),
        migrations.CreateModel(
            name="MissionLevel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("level_no", models.IntegerField()),
                ("level_name", models.CharField(max_length=100)),
                ("level_type", models.CharField(max_length=30)),
                ("pass_rule_json", models.JSONField(default=dict)),
                ("mode_policy", models.CharField(blank=True, max_length=50, null=True)),
                ("hint_strength", models.CharField(default="medium", max_length=20)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="missions.learningmission",
                    ),
                ),
            ],
            options={
                "db_table": "mission_level",
                "ordering": ["level_no"],
            },
        ),
        migrations.CreateModel(
            name="MissionQuestionRel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question_id", models.IntegerField()),
                ("sort_no", models.IntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "source_type",
                    models.CharField(default="manual_select", max_length=20),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.missionlevel",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.learningmission",
                    ),
                ),
            ],
            options={
                "db_table": "mission_question_rel",
                "ordering": ["sort_no"],
            },
        ),
    ]
