# Generated by Django 5.2.15 on 2026-06-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0001_initial"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmission",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                db_column="class_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_missions",
                to="institutions.class",
                verbose_name="所属班级",
            ),
        ),
    ]
