# Generated by Django 5.2.16 on 2026-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0008_p1_mission_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionquestionrel",
            name="question_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
