# Generated by Django 5.2.16 on 2026-08-29 14:54

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0004_class_grade_level"),
        ("missions", "0009_missionquestionrel_question_snapshot"),
        ("wrongbook", "0002_alter_wrongbookitem_question_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedQuestionRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_question_id", models.UUIDField()),
                ("candidate_question_id", models.UUIDField()),
                (
                    "provider",
                    models.CharField(
                        choices=[("rule", "rule"), ("ai", "ai")], max_length=20
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "suggested"),
                            ("teacher_selected", "teacher_selected"),
                            ("rejected", "rejected"),
                            ("discarded", "discarded"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                (
                    "discard_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("result_json", models.JSONField(blank=True, default=dict)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "related_question_recommendation",
            },
        ),
        migrations.CreateModel(
            name="RelatedQuestionRecommendationCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(default="ai", max_length=20)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("request_json", models.JSONField(blank=True, default=dict)),
                ("returned_count", models.PositiveIntegerField(default=0)),
                ("call_count", models.PositiveIntegerField(default=1)),
                ("cost_json", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "related_question_recommendation_call",
            },
        ),
        migrations.CreateModel(
            name="TeacherWrongBookCell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_question_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("marked", "marked"),
                            ("cancelled", "cancelled"),
                            ("generated", "generated"),
                            ("locked", "locked"),
                        ],
                        default="marked",
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("generated_batch_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher_wrongbook_cell",
            },
        ),
        migrations.CreateModel(
            name="TeacherWrongBookMatrix",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("saved", "saved"),
                            ("generating", "generating"),
                            ("generated", "generated"),
                            ("partially_failed", "partially_failed"),
                            ("scope_changed", "scope_changed"),
                            ("closed", "closed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("marked_count", models.PositiveIntegerField(default=0)),
                ("generated_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("last_generation_batch_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teacher_wrongbook_matrix",
            },
        ),
        migrations.CreateModel(
            name="TeacherWrongBookMatrixAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("scope_created", "scope_created"),
                            ("scope_refreshed", "scope_refreshed"),
                            ("mark_saved", "mark_saved"),
                            ("mark_cancelled", "mark_cancelled"),
                            ("generation_requested", "generation_requested"),
                            ("generation_completed", "generation_completed"),
                            ("recommendation_requested", "recommendation_requested"),
                            ("recommendation_confirmed", "recommendation_confirmed"),
                            ("retry_requested", "retry_requested"),
                            ("matrix_closed", "matrix_closed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("version", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "teacher_wrongbook_matrix_audit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherWrongBookMatrixQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_question_id", models.UUIDField()),
                (
                    "question_no_snapshot",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("sort_no", models.PositiveIntegerField(default=0)),
                ("question_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("removed", "removed")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_wrongbook_matrix_question",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="TeacherWrongBookMatrixStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_assignment_id", models.UUIDField(blank=True, null=True)),
                (
                    "student_name_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "student_no_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "class_name_snapshot",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("sort_no", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("removed", "removed")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_wrongbook_matrix_student",
                "ordering": ["sort_no", "student_name_snapshot", "id"],
            },
        ),
        migrations.CreateModel(
            name="WrongBookGenerationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("generating", "generating"),
                            ("snapshotting", "snapshotting"),
                            ("publishing", "publishing"),
                            ("published", "published"),
                            ("partially_failed", "partially_failed"),
                            ("failed", "failed"),
                            ("retrying", "retrying"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("related_limit", models.PositiveSmallIntegerField(default=3)),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("generated_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("published_task_count", models.PositiveIntegerField(default=0)),
                ("error_json", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "wrongbook_generation_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WrongBookGenerationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_question_id", models.UUIDField()),
                ("related_question_ids", models.JSONField(blank=True, default=list)),
                ("selected_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "shortage_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("generating", "generating"),
                            ("generated", "generated"),
                            ("snapshot_failed", "snapshot_failed"),
                            ("published", "published"),
                            ("publish_failed", "publish_failed"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "wrongbook_generation_item",
            },
        ),
        migrations.AddField(
            model_name="learningmission",
            name="parent_mission_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="learningmission",
            name="source_generation_batch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="learningmission",
            name="source_matrix_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_matrix_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_provider",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_role",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_student_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_wrong_book_item_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="missionquestionrel",
            constraint=models.UniqueConstraint(
                fields=(
                    "mission",
                    "source_student_id",
                    "question_id",
                    "source_wrong_book_item_id",
                ),
                name="uq_mission_phase4_source_question",
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="confirmed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_wrongbook_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_wrongbook_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="source_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="source_wrong_book_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendations",
                to="wrongbook.wrongbookitem",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_wrongbook_cells",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="source_relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrix_cells",
                to="missions.missionquestionrel",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrix_cells",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="wrong_book_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacher_matrix_cells",
                to="wrongbook.wrongbookitem",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrix",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                db_column="class_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_matrices",
                to="institutions.class",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrix",
            name="creator_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrix",
            name="source_mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrices",
                to="missions.learningmission",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendationcall",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_calls",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixaudit",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_matrix_audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixaudit",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="source_relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrix_questions",
                to="missions.missionquestionrel",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixstudent",
            name="class_obj",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="institutions.class",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixstudent",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_matrix_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationbatch",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_batches",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationbatch",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_generation_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixaudit",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="missions.wrongbookgenerationbatch",
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendationcall",
            name="source_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_calls",
                to="missions.wrongbookgenerationbatch",
            ),
        ),
        migrations.AddField(
            model_name="relatedquestionrecommendation",
            name="source_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="missions.wrongbookgenerationbatch",
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="missions.wrongbookgenerationbatch",
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="cell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_items",
                to="missions.teacherwrongbookcell",
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="source_wrong_book_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generation_items",
                to="wrongbook.wrongbookitem",
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wrongbook_generation_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="target_mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_generation_items",
                to="missions.learningmission",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookmatrix",
            constraint=models.UniqueConstraint(
                fields=("source_mission",), name="uq_wrongbook_matrix_source_mission"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookcell",
            constraint=models.UniqueConstraint(
                fields=("matrix", "student", "source_question_id"),
                name="uq_wrongbook_matrix_cell",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookmatrixquestion",
            constraint=models.UniqueConstraint(
                fields=("matrix", "source_question_id"),
                name="uq_wrongbook_matrix_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookmatrixstudent",
            constraint=models.UniqueConstraint(
                fields=("matrix", "student", "class_obj"),
                name="uq_wrongbook_matrix_student_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrongbookgenerationbatch",
            constraint=models.UniqueConstraint(
                fields=("matrix", "idempotency_key"),
                name="uq_wrongbook_generation_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="relatedquestionrecommendation",
            constraint=models.UniqueConstraint(
                fields=(
                    "matrix",
                    "source_batch",
                    "source_student",
                    "source_question_id",
                    "candidate_question_id",
                ),
                name="uq_wrongbook_recommendation_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrongbookgenerationitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "cell"), name="uq_wrongbook_generation_item_cell"
            ),
        ),
    ]
