# Generated by Django 5.2.16 on 2026-08-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0010_relatedquestionrecommendation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrongbookgenerationbatch",
            name="ai_confirmation_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="wrongbookgenerationbatch",
            name="ai_supplement_mission_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
