# Generated by Django 5.2.16 on 2026-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0011_wrongbookgenerationbatch_ai_confirmation_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrongbookgenerationbatch",
            name="request_cell_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
