# Generated by Django 5.2.16 on 2026-08-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0012_wrongbookgenerationbatch_request_cell_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrongbookgenerationitem",
            name="error_stage",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
