# Generated by Django 5.2.15 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0016_teacher_wrongbook_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedquestionrecommendation',
            name='provider',
            field=models.CharField(
                choices=[
                    ('rule', 'rule'), ('ai', 'ai'),
                    ('relation', 'relation'), ('criteria', 'criteria'),
                ],
                max_length=20,
            ),
        ),
    ]
