# Generated by Django 5.2.16 on 2026-09-14 11:36

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


def backfill_classroom_provenance(apps, schema_editor):
    LearningMission = apps.get_model('missions', 'LearningMission')
    CourseTree = apps.get_model('courses', 'CourseTree')
    CourseQuestionLink = apps.get_model('courses', 'CourseQuestionLink')
    MissionLevel = apps.get_model('missions', 'MissionLevel')
    MissionQuestionRel = apps.get_model('missions', 'MissionQuestionRel')
    MatrixQuestion = apps.get_model('missions', 'TeacherWrongBookMatrixQuestion')

    missions = LearningMission.objects.filter(
        source_context='course_practice', course_id__isnull=False,
    )
    for mission in missions.iterator():
        node_ids = [str(value) for value in (mission.source_node_ids or []) if value]
        node_map = {
            str(node.id): node
            for node in CourseTree.objects.filter(course_id=mission.course_id, id__in=node_ids)
        }
        levels = list(MissionLevel.objects.filter(mission_id=mission.id).order_by('level_no', 'id'))
        level_nodes = {}
        for index, level in enumerate(levels):
            node_id = str(level.source_node_id) if level.source_node_id else (
                node_ids[index] if index < len(node_ids) else ''
            )
            node = node_map.get(node_id)
            if not node_id or node is None:
                continue
            level.source_node_id = node.id
            level.node_name_snapshot = node.name
            level.node_sort_no_snapshot = index + 1
            level.save(update_fields=['source_node_id', 'node_name_snapshot', 'node_sort_no_snapshot'])
            level_nodes[level.id] = (node.id, node.name, index + 1)

        relation_groups = {}
        relations = MissionQuestionRel.objects.filter(mission_id=mission.id).order_by('level_id', 'sort_no', 'id')
        for relation in relations:
            relation_groups.setdefault(relation.level_id, []).append(relation)
        for level_id, rows in relation_groups.items():
            node_info = level_nodes.get(level_id)
            if not node_info:
                continue
            node_id, node_name, _ = node_info
            for position, relation in enumerate(rows, 1):
                relation.source_node_id = node_id
                relation.source_node_name_snapshot = node_name
                relation.node_question_no = str(position)
                relation.save(update_fields=['source_node_id', 'source_node_name_snapshot', 'node_question_no'])

        for matrix_question in MatrixQuestion.objects.filter(matrix__source_mission_id=mission.id):
            relation = MissionQuestionRel.objects.filter(
                mission_id=mission.id, question_id=matrix_question.source_question_id,
            ).order_by('sort_no', 'id').first()
            if relation is None:
                continue
            matrix_question.source_node_id = relation.source_node_id
            matrix_question.node_name_snapshot = relation.source_node_name_snapshot
            matrix_question.node_question_no = relation.node_question_no
            matrix_question.node_sort_no = relation.level.node_sort_no_snapshot if relation.level_id else 0
            matrix_question.question_no_snapshot = relation.node_question_no or matrix_question.question_no_snapshot
            matrix_question.save(update_fields=[
                'source_node_id', 'node_name_snapshot', 'node_question_no',
                'node_sort_no', 'question_no_snapshot',
            ])


def reverse_backfill_classroom_provenance(apps, schema_editor):
    # Snapshot fields are additive and intentionally retained on rollback.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0006_studentimportrow_target_class"),
        ("missions", "0018_learningmission_source_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherWrongBookImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("validating", "validating"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="validating",
                        max_length=20,
                    ),
                ),
                ("sheet_count", models.PositiveIntegerField(default=0)),
                ("total_cells", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                (
                    "replace_scope",
                    models.CharField(
                        default="offline_students_in_uploaded_nodes", max_length=80
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teacher_wrongbook_import_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="teacherwrongbookmatrix",
            name="uq_wrongbook_matrix_source_mission",
        ),
        migrations.AddField(
            model_name="missionlevel",
            name="node_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="missionlevel",
            name="node_sort_no_snapshot",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="missionlevel",
            name="source_node_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="node_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_node_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_node_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="teacherwrongbookcell",
            name="mark_source",
            field=models.CharField(
                choices=[
                    ("online", "online"),
                    ("manual", "manual"),
                    ("import", "import"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="node_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="node_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="node_sort_no",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacherwrongbookmatrixquestion",
            name="source_node_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_classroom_provenance, reverse_backfill_classroom_provenance),
        migrations.AlterField(
            model_name="teacherwrongbookcell",
            name="source_relation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_matrix_cells",
                to="missions.missionquestionrel",
            ),
        ),
        migrations.AlterField(
            model_name="teacherwrongbookmatrixaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("scope_created", "scope_created"),
                    ("scope_refreshed", "scope_refreshed"),
                    ("mark_saved", "mark_saved"),
                    ("mark_cancelled", "mark_cancelled"),
                    ("import_succeeded", "import_succeeded"),
                    ("import_failed", "import_failed"),
                    ("generation_requested", "generation_requested"),
                    ("generation_completed", "generation_completed"),
                    ("recommendation_requested", "recommendation_requested"),
                    ("recommendation_confirmed", "recommendation_confirmed"),
                    ("retry_requested", "retry_requested"),
                    ("matrix_closed", "matrix_closed"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="teacherwrongbookmatrixquestion",
            name="source_relation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_matrix_questions",
                to="missions.missionquestionrel",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookmatrix",
            constraint=models.UniqueConstraint(
                condition=models.Q(("class_obj__isnull", True)),
                fields=("source_mission",),
                name="uq_wrongbook_matrix_source_mission_null_class",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherwrongbookmatrix",
            constraint=models.UniqueConstraint(
                condition=models.Q(("class_obj__isnull", False)),
                fields=("source_mission", "class_obj"),
                name="uq_wrongbook_matrix_source_mission_class",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookimportbatch",
            name="matrix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_batches",
                to="missions.teacherwrongbookmatrix",
            ),
        ),
        migrations.AddField(
            model_name="teacherwrongbookimportbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wrongbook_import_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
