# Generated by Django 5.2.16 on 2026-09-14 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0019_classroom_wrongbook_statistics"),
        ("wrongbook", "0002_alter_wrongbookitem_question_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionlevel",
            name="node_sort_no_snapshot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="teacherwrongbookcell",
            index=models.Index(
                fields=["matrix", "mark_source", "status"],
                name="idx_twb_cell_src_status",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherwrongbookcell",
            index=models.Index(
                fields=["matrix", "student", "status"],
                name="idx_twb_cell_student_status",
            ),
        ),
    ]
