# Generated by Django 5.2.16 on 2026-09-16 04:06

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0020_classroom_wrongbook_statistics_indexes"),
        ("parser", "0010_question_document_source_fingerprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmission",
            name="source_batch_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="learningmission",
            name="source_set_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_drill_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_mapping_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_set_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_wrong_question_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="missionquestionrel",
            name="source_wrong_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_version", models.PositiveIntegerField()),
                ("request_student_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("generating", "generating"),
                            ("generated", "generated"),
                            ("partially_failed", "partially_failed"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("requested_count", models.PositiveIntegerField(default=0)),
                ("generated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_batches",
                        to="missions.teacherwrongbookmatrix",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "generated"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "pdf_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("question_count", models.PositiveIntegerField(default=0)),
                ("missing_count", models.PositiveIntegerField(default=0)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="missions.classroomwrongdrillbatch",
                    ),
                ),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_package",
                        to="missions.learningmission",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_package",
            },
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillSourceQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wrong_question_no", models.CharField(max_length=50)),
                ("question_snapshot", models.JSONField(blank=True, default=dict)),
                ("answer_snapshot", models.TextField(blank=True, default="")),
                ("analysis_snapshot", models.TextField(blank=True, default="")),
                ("sort_no", models.PositiveIntegerField(default=0)),
                ("parse_status", models.CharField(default="imported", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wrong_drill_source_questions",
                        to="parser.examquestion",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_source_question",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillNumberMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wrong_question_no", models.CharField(max_length=50)),
                ("workbook_question_no", models.CharField(max_length=50)),
                (
                    "workbook_question_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("invalid", "invalid"),
                            ("unmatched", "unmatched"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("mapping_version", models.PositiveIntegerField(default=1)),
                ("sort_no", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="number_mappings",
                        to="missions.classroomwrongdrillsourcequestion",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_number_mapping",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wrong_question_no", models.CharField(max_length=50)),
                ("drill_question_no", models.CharField(max_length=50)),
                ("sort_no", models.PositiveIntegerField(default=0)),
                (
                    "answer_source",
                    models.CharField(
                        blank=True, default="exam_question", max_length=30
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "generated"),
                            ("missing_mapping", "missing_mapping"),
                            ("missing_answer", "missing_answer"),
                        ],
                        default="generated",
                        max_length=30,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drill_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wrong_drill_items",
                        to="parser.examquestion",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_items",
                        to="missions.classroomwrongdrillnumbermapping",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="missions.classroomwrongdrillpackage",
                    ),
                ),
                (
                    "source_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_items",
                        to="missions.classroomwrongdrillsourcequestion",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_item",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillSourceSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_node_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "source_node_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "workbook_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("workbook_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "source_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "import_purpose",
                    models.CharField(default="wrongbook_drill", max_length=40),
                ),
                (
                    "source_type",
                    models.CharField(default="wrongbook_drill", max_length=40),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("ready", "ready"),
                            ("pending_mapping", "pending_mapping"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("number_mapping_version", models.PositiveIntegerField(default=0)),
                (
                    "error_summary",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_source_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_drill_source_sets",
                        to="missions.learningmission",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_source_set",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="classroomwrongdrillsourcequestion",
            name="source_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="missions.classroomwrongdrillsourceset",
            ),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillnumbermapping",
            name="source_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="number_mappings",
                to="missions.classroomwrongdrillsourceset",
            ),
        ),
        migrations.CreateModel(
            name="ClassroomWrongDrillMappingImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("validating", "validating"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="validating",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("invalid_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wrong_drill_mapping_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_imports",
                        to="missions.classroomwrongdrillsourceset",
                    ),
                ),
            ],
            options={
                "db_table": "classroom_wrong_drill_mapping_import",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="classroomwrongdrillbatch",
            name="source_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generation_batches",
                to="missions.classroomwrongdrillsourceset",
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillpackage",
            constraint=models.UniqueConstraint(
                fields=("batch", "student"), name="uq_cwdp_batch_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillitem",
            constraint=models.UniqueConstraint(
                fields=("package", "source_question"), name="uq_cwdi_package_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillsourcequestion",
            constraint=models.UniqueConstraint(
                fields=("source_set", "wrong_question_no"), name="uq_cwdsq_set_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillnumbermapping",
            constraint=models.UniqueConstraint(
                fields=("source_set", "wrong_question_no"), name="uq_cwdnm_set_wrong_no"
            ),
        ),
    ]
