# Generated by Django 5.2.16 on 2026-09-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0021_learningmission_source_batch_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroomwrongdrillitem",
            name="relation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillpackage",
            name="class_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillpackage",
            name="number_mapping_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillpackage",
            name="source_statistics_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillpackage",
            name="student_name_snapshot",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
