# Generated by Django 5.2.15 on 2026-09-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0022_classroomwrongdrillitem_relation_snapshot_and_more"),
        ("parser", "0010_question_document_source_fingerprint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classroomwrongdrillitem",
            name="uq_cwdi_package_source",
        ),
        migrations.RemoveConstraint(
            model_name="classroomwrongdrillnumbermapping",
            name="uq_cwdnm_set_wrong_no",
        ),
        migrations.AddField(
            model_name="classroomwrongdrillitem",
            name="content_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillitem",
            name="mapping_type",
            field=models.CharField(default="wrong_drill", max_length=20),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillitem",
            name="original_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wrong_drill_original_items",
                to="parser.examquestion",
            ),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillnumbermapping",
            name="display_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillnumbermapping",
            name="mapping_type",
            field=models.CharField(
                choices=[("wrong_drill", "wrong_drill"), ("original", "original")],
                default="wrong_drill",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="classroomwrongdrillnumbermapping",
            name="original_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wrong_drill_original_mappings",
                to="parser.examquestion",
            ),
        ),
        migrations.AlterField(
            model_name="classroomwrongdrillitem",
            name="source_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_items",
                to="missions.classroomwrongdrillsourcequestion",
            ),
        ),
        migrations.AlterField(
            model_name="classroomwrongdrillnumbermapping",
            name="source_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="number_mappings",
                to="missions.classroomwrongdrillsourcequestion",
            ),
        ),
        migrations.AlterField(
            model_name="classroomwrongdrillnumbermapping",
            name="wrong_question_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillitem",
            constraint=models.UniqueConstraint(
                fields=("package", "mapping"), name="uq_cwdi_package_mapping"
            ),
        ),
        migrations.AddConstraint(
            model_name="classroomwrongdrillnumbermapping",
            constraint=models.UniqueConstraint(
                fields=("source_set", "workbook_question_no"),
                name="uq_cwdnm_set_workbook_no",
            ),
        ),
    ]
