<template>
  <view class="page">
    <view class="header"><text class="title">错题练习</text><view><button size="mini" @click="load">刷新</button><button size="mini" @click="showHistory = true">导入历史</button><button size="mini" type="primary" :disabled="uploading" @click="chooseFile">{{ uploading ? '正在提交...' : '导入错题练习题' }}</button></view></view>
    <view v-if="currentTask" class="import-status"><text>最近导入：{{ currentSource?.source_file_name || '错题练习题' }}</text><text>状态：{{ stageText(currentTask.stage) }} · {{ currentTask.progress || 0 }}%</text><text>成功 {{ currentTask.success_count || 0 }} 题，失败 {{ currentTask.failed_question_count || 0 }} 题</text><text v-if="currentTask.error_summary" class="error-text">{{ currentTask.error_summary }}</text></view>
    <view v-if="loading" class="empty">正在加载...</view><view v-else-if="!questions.length" class="empty">当前暂未导入错题练习题</view>
    <view v-else class="question-list"><view v-for="item in questions" :key="item.question_id" class="question-card"><text class="number">{{ item.question_no }}.</text><view class="question-body"><rich-text class="stem" :nodes="item.snapshot?.stem || item.snapshot?.content || '题干解析中'" /><view v-if="item.snapshot?.image_items?.length" class="question-images"><image v-for="(image, index) in item.snapshot.image_items" :key="image.id || image.url || index" class="question-image" :src="image.url" :style="{ width: `${Math.min(Math.max(Number(image.display_width) || 100, 1), 100)}%` }" mode="widthFix" /></view><view v-if="item.snapshot?.options" class="options"><text v-for="(value, key) in item.snapshot.options" :key="key">{{ key }}. {{ value }}</text></view></view></view></view>
    <view v-if="showHistory" class="overlay" @click.self="showHistory = false"><view class="history"><view class="history-head"><text>错题练习题导入历史</text><text @click="showHistory = false">×</text></view><view v-if="!sources.length" class="empty small">暂无导入记录</view><view v-for="source in sources" :key="source.source_set_id" class="history-row"><text class="file">{{ source.source_file_name || '处理中，等待文件信息' }}</text><text>状态：{{ stageText(source.import_task?.stage || source.status) }} · {{ source.import_task?.progress || 0 }}%</text><text>成功 {{ source.import_task?.success_count || 0 }} 题，失败 {{ source.import_task?.failed_question_count || 0 }} 题</text><text v-if="source.error_summary || source.import_task?.error_summary" class="error-text">{{ source.error_summary || source.import_task?.error_summary }}</text></view></view></view>
  </view>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad, onUnload } from '@dcloudio/uni-app'; import { courseApi } from '@/api/courses'; import { classroomWrongbookApi } from '@/api/classroom-wrongbook'
const courseId=ref(''),missionId=ref(''),classId=ref(''),sourceId=ref(''),questions=ref<any[]>([]),sources=ref<any[]>([]),loading=ref(false),uploading=ref(false),showHistory=ref(false);let timer:any
const currentSource=computed(()=>sources.value.find(item=>item.source_set_id===sourceId.value)||sources.value[0]);const currentTask=computed(()=>currentSource.value?.import_task||null)
onLoad(async(o:any)=>{courseId.value=String(o?.course_id||'');await load()});onUnload(()=>timer&&clearTimeout(timer))
async function load(){if(!courseId.value)return;loading.value=true;try{const c:any=await courseApi.wrongDrillContext(courseId.value as any),d=c?.data||c;missionId.value=d.mission_id;classId.value=d.class_ids?.[0]||'';const r:any=await classroomWrongbookApi.wrongDrillSources(missionId.value,classId.value?{class_id:classId.value}:undefined);sources.value=r?.data?.sources||[];sourceId.value=sources.value.some(item=>item.source_set_id===sourceId.value)?sourceId.value:(sources.value[0]?.source_set_id||'');if(sourceId.value){const detail:any=await classroomWrongbookApi.wrongDrillSourceDetail(missionId.value,sourceId.value,classId.value);questions.value=detail?.data?.questions||[]}else questions.value=[];if(['queued','extracting','structuring','importing'].includes(currentTask.value?.stage))poll()}catch(e:any){uni.showToast({title:e?.message||'加载失败',icon:'none'})}finally{loading.value=false}}
function poll(){if(timer)clearTimeout(timer);timer=setTimeout(load,2000)}function stageText(s?:string){return ({queued:'排队中',extracting:'提取文档中',structuring:'解析题目中',importing:'入库中',succeeded:'导入完成',failed:'导入失败',pending:'等待处理',pending_mapping:'等待映射',ready:'已就绪'} as Record<string,string>)[s||'']||s||'未知'}
function chooseFile(){const done=(r:any)=>upload(r?.tempFiles?.[0]?.path);// #ifdef MP-WEIXIN
uni.chooseMessageFile({count:1,type:'file',success:done});// #endif
// #ifndef MP-WEIXIN
;(uni as any).chooseFile({count:1,extension:['docx'],success:done});// #endif
}async function upload(path?:string){if(!path||!missionId.value)return;uploading.value=true;try{const r:any=await classroomWrongbookApi.uploadWrongDrill(missionId.value,path,{class_id:classId.value});sourceId.value=r?.data?.source_set_id||'';uni.showToast({title:'导入已提交',icon:'success'});await load()}catch(e:any){uni.showToast({title:e?.message||'导入失败',icon:'none'})}finally{uploading.value=false}}
</script>
<style scoped>.page{min-height:100vh;padding:30rpx;background:#f5f7fa;box-sizing:border-box}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24rpx}.title{font-size:36rpx;font-weight:600;color:#303133}.header button{margin-left:12rpx}.import-status{display:flex;gap:24rpx;flex-wrap:wrap;margin-bottom:20rpx;padding:18rpx 22rpx;background:#ecf5ff;border-radius:8rpx;color:#409eff;font-size:24rpx}.empty{padding:150rpx 0;text-align:center;color:#909399}.question-list{max-width:1100rpx;margin:auto}.question-card{display:flex;gap:14rpx;margin-bottom:18rpx;padding:28rpx;background:#fff;border-radius:12rpx;color:#303133}.number{font-weight:600}.question-body{min-width:0;flex:1}.stem{line-height:1.75}.question-images{margin:18rpx 0}.question-image{display:block;max-width:100%;margin:0 0 16rpx;border-radius:6rpx}.options{display:flex;flex-direction:column;gap:8rpx;color:#606266;font-size:25rpx}.overlay{position:fixed;inset:0;z-index:10;background:rgba(0,0,0,.35);display:flex;align-items:center;justify-content:center}.history{width:760rpx;max-height:70vh;overflow:auto;background:#fff;border-radius:12rpx;padding:26rpx}.history-head{display:flex;justify-content:space-between;font-size:30rpx;font-weight:600}.history-head text:last-child{font-size:42rpx;color:#909399}.history-row{display:flex;flex-direction:column;gap:9rpx;padding:20rpx 0;border-bottom:1rpx solid #ebeef5;color:#606266;font-size:24rpx}.file{color:#303133;font-weight:500}.small{padding:50rpx}.error-text{color:#f56c6c}</style>
