<template>
<view class="page"><view class="header"><text class="title">错题映射</text><view><button size="mini" @click="load">刷新</button><button size="mini" @click="showHistory=true">导入历史</button><button size="mini" :disabled="uploading" @click="chooseFile">{{uploading?'正在导入...':'导入映射关系表'}}</button><button v-if="rows.length&&editing" size="mini" type="primary" :disabled="saving" @click="save">保存</button><button v-if="rows.length" size="mini" :disabled="saving" @click="editing=!editing">{{editing?'取消编辑':'编辑'}}</button></view></view>
<view v-if="latestImport" class="import-status"><text>最近导入：{{latestImport.file_name}}</text><text>状态：{{statusText(latestImport.status)}}</text><text>共 {{latestImport.total_rows||0}} 行，成功 {{latestImport.imported_count||0}} 行，失败 {{latestImport.invalid_count||0}} 行</text></view>
<view v-if="loading" class="empty">正在加载...</view><view v-else-if="!rows.length" class="empty">当前暂未导入错题映射表</view><view v-else class="table"><view class="tr head"><text>序号</text><text>错题练习题号</text><text>针对练习册题号</text></view><view v-for="(row,index) in rows" :key="row.mapping_id||index" class="tr"><text>{{index+1}}</text><input v-if="editing" v-model="row.wrong_question_no"/><text v-else>{{row.wrong_question_no}}</text><input v-if="editing" v-model="row.workbook_question_no"/><text v-else>{{row.workbook_question_no}}</text></view></view>
<view v-if="showHistory" class="overlay" @click.self="showHistory=false"><view class="history"><view class="history-head"><text>映射关系表导入历史</text><text @click="showHistory=false">×</text></view><view v-if="!mappingHistory.length" class="empty small">暂无导入记录</view><view v-for="item in mappingHistory" :key="item.source_set_id" class="history-row"><text class="file">{{item.mapping_import.file_name}}</text><text>状态：{{statusText(item.mapping_import.status)}}</text><text>共 {{item.mapping_import.total_rows||0}} 行，成功 {{item.mapping_import.imported_count||0}} 行，失败 {{item.mapping_import.invalid_count||0}} 行</text><text v-if="item.mapping_import.errors?.length" class="error-text">存在 {{item.mapping_import.errors.length}} 条校验错误</text></view></view></view></view>
</template>
<script setup lang="ts">
import {computed,ref} from 'vue';import {onLoad} from '@dcloudio/uni-app';import {courseApi} from '@/api/courses';import {classroomWrongbookApi} from '@/api/classroom-wrongbook'
const courseId=ref(''),missionId=ref(''),classId=ref(''),sourceId=ref(''),rows=ref<any[]>([]),sources=ref<any[]>([]),loading=ref(false),uploading=ref(false),editing=ref(false),saving=ref(false),showHistory=ref(false)
const activeSource=computed(()=>sources.value.find(x=>x.source_set_id===sourceId.value)||sources.value[0]);const latestImport=computed(()=>activeSource.value?.mapping_import||null);const mappingHistory=computed(()=>sources.value.filter(x=>x.mapping_import))
onLoad(async(o:any)=>{courseId.value=String(o?.course_id||'');await load()})
async function context(){const r:any=await courseApi.wrongDrillContext(courseId.value as any),d=r?.data||r;missionId.value=d.mission_id;classId.value=d.class_ids?.[0]||''}
async function load(){if(!courseId.value)return;loading.value=true;try{await context();const r:any=await classroomWrongbookApi.wrongDrillSources(missionId.value,classId.value?{class_id:classId.value}:undefined);sources.value=r?.data?.sources||[];sourceId.value=sources.value.some(x=>x.source_set_id===sourceId.value)?sourceId.value:(sources.value[0]?.source_set_id||'');if(sourceId.value){const d:any=await classroomWrongbookApi.wrongDrillSourceDetail(missionId.value,sourceId.value,classId.value);rows.value=(d?.data?.mappings||[]).map((x:any)=>({...x}))}else rows.value=[]}catch(e:any){uni.showToast({title:e?.message||'加载失败',icon:'none'})}finally{loading.value=false}}
function statusText(s?:string){return ({validating:'校验中',succeeded:'导入完成',failed:'导入失败',pending:'等待处理',ready:'已就绪'}as Record<string,string>)[s||'']||s||'未知'}
function chooseFile(){if(!sourceId.value){uni.showToast({title:'请先导入错题练习题',icon:'none'});return}const done=(r:any)=>upload(r?.tempFiles?.[0]?.path);// #ifdef MP-WEIXIN
uni.chooseMessageFile({count:1,type:'file',success:done});// #endif
// #ifndef MP-WEIXIN
;(uni as any).chooseFile({count:1,extension:['xlsx'],success:done});// #endif
}async function upload(path?:string){if(!path)return;uploading.value=true;try{await classroomWrongbookApi.uploadWrongDrillMapping(missionId.value,sourceId.value,path,classId.value);uni.showToast({title:'映射表已导入',icon:'success'});await load()}catch(e:any){uni.showToast({title:e?.message||'导入失败',icon:'none'})}finally{uploading.value=false}}
async function save(){saving.value=true;try{const r:any=await classroomWrongbookApi.saveWrongDrillMappings(missionId.value,sourceId.value,{class_id:classId.value,mappings:rows.value});rows.value=(r?.data?.mappings||[]).map((x:any)=>({...x}));editing.value=false;uni.showToast({title:'映射关系已保存',icon:'success'});await load()}catch(e:any){uni.showToast({title:e?.message||'保存失败',icon:'none'})}finally{saving.value=false}}
</script>
<style scoped>.page{min-height:100vh;padding:30rpx;background:#f5f7fa;box-sizing:border-box}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24rpx}.title{font-size:36rpx;font-weight:600}.header button{margin-left:12rpx}.import-status{display:flex;gap:24rpx;flex-wrap:wrap;margin-bottom:20rpx;padding:18rpx 22rpx;background:#ecf5ff;border-radius:8rpx;color:#409eff;font-size:24rpx}.empty{padding:150rpx 0;text-align:center;color:#909399}.table{background:#fff;border-radius:12rpx;overflow:hidden}.tr{display:grid;grid-template-columns:120rpx 1fr 1fr;gap:16rpx;padding:20rpx;border-bottom:1rpx solid #ebeef5;align-items:center}.head{font-weight:600;background:#f5f7fa}.tr input{border:1rpx solid #dcdfe6;border-radius:6rpx;padding:8rpx 12rpx;font-size:26rpx}.overlay{position:fixed;inset:0;z-index:10;background:rgba(0,0,0,.35);display:flex;align-items:center;justify-content:center}.history{width:760rpx;max-height:70vh;overflow:auto;background:#fff;border-radius:12rpx;padding:26rpx}.history-head{display:flex;justify-content:space-between;font-size:30rpx;font-weight:600}.history-head text:last-child{font-size:42rpx;color:#909399}.history-row{display:flex;flex-direction:column;gap:9rpx;padding:20rpx 0;border-bottom:1rpx solid #ebeef5;color:#606266;font-size:24rpx}.file{color:#303133;font-weight:500}.small{padding:50rpx}.error-text{color:#f56c6c}</style>
