# Generated by Django 5.0.14 on 2026-05-05 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="试卷名称")),
                ("subject", models.CharField(max_length=50, verbose_name="学科")),
                (
                    "stage",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学段"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="年级"
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="试卷类型"
                    ),
                ),
                (
                    "has_solution",
                    models.BooleanField(default=False, verbose_name="是否含答案解析"),
                ),
                (
                    "source_file_path",
                    models.CharField(max_length=500, verbose_name="源文件路径"),
                ),
                (
                    "pdf_file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="PDF路径"
                    ),
                ),
                ("total_pages", models.IntegerField(default=0, verbose_name="总页数")),
                ("total_questions", models.IntegerField(default=0, verbose_name="总题数")),
                (
                    "status",
                    models.CharField(
                        default="uploaded", max_length=50, verbose_name="状态"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "试卷",
                "verbose_name_plural": "试卷",
                "db_table": "tiku_exam_paper",
            },
        ),
        migrations.CreateModel(
            name="ParseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="状态"
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="当前步骤"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="papers.exampaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "解析任务",
                "verbose_name_plural": "解析任务",
                "db_table": "tiku_parse_task",
                "indexes": [models.Index(fields=["status"], name="idx_task_status")],
            },
        ),
    ]
