# Generated by Django 5.2.16 on 2026-07-23 12:38

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionIDCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=50, unique=True)),
                ("next_seq", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "题目系统编号计数器",
                "verbose_name_plural": "题目系统编号计数器",
                "db_table": "tiku_question_id_counter",
            },
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="试卷名称")),
                (
                    "paper_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="如：M90001, PA0002",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="试卷编号",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="如：全国卷, 广东卷, 深圳卷",
                        max_length=100,
                        null=True,
                        verbose_name="来源地区",
                    ),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="学科")),
                (
                    "stage",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="学段"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="年级"
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="试卷类型"
                    ),
                ),
                (
                    "has_solution",
                    models.BooleanField(default=False, verbose_name="是否含答案解析"),
                ),
                (
                    "source_file_path",
                    models.CharField(max_length=500, verbose_name="源文件路径"),
                ),
                (
                    "pdf_file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="PDF路径"
                    ),
                ),
                ("total_pages", models.IntegerField(default=0, verbose_name="总页数")),
                ("total_questions", models.IntegerField(default=0, verbose_name="总题数")),
                (
                    "status",
                    models.CharField(
                        default="uploaded", max_length=50, verbose_name="状态"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="已删除"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="上传该试卷的老师",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_papers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "试卷",
                "verbose_name_plural": "试卷",
                "db_table": "tiku_exam_paper",
            },
        ),
        migrations.CreateModel(
            name="PaperCodeCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("letter", models.CharField(max_length=1)),
                ("grade_char", models.CharField(max_length=1)),
                ("next_seq", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "试卷编号计数器",
                "verbose_name_plural": "试卷编号计数器",
                "db_table": "tiku_paper_code_counter",
                "unique_together": {("letter", "grade_char")},
            },
        ),
        migrations.CreateModel(
            name="ParseTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=50, verbose_name="状态"
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="当前步骤"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        db_column="paper_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="papers.exampaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "解析任务",
                "verbose_name_plural": "解析任务",
                "db_table": "tiku_parse_task",
            },
        ),
    ]
