# Generated by Django 5.2.16 on 2026-07-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("papers", "0001_initial"),
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_column="question_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reparse_tasks",
                to="parser.examquestion",
                verbose_name="试题",
            ),
        ),
        migrations.AddIndex(
            model_name="parsetask",
            index=models.Index(fields=["status"], name="idx_task_status"),
        ),
    ]
