# Generated by Django 5.0.14 on 2026-05-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0003_backfill_paper_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampaper",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False, verbose_name="已删除"),
        ),
    ]
