# Generated by Django 5.0.14 on 2026-05-12 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0004_exampaper_is_deleted"),
        ("parser", "0004_backfill_question_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="parsetask",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_column="question_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reparse_tasks",
                to="parser.examquestion",
                verbose_name="试题",
            ),
        ),
    ]
