# Generated by Django 5.0.14 on 2026-06-19 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0005_add_question_fk_to_parse_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exampaper",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="上传该试卷的老师",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_papers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
    ]
