# Generated by Django 5.2.16 on 2026-08-28 07:49

import django.db.models.deletion
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0004_courseclass_coursehandout"),
        ("parser", "0007_examquestion_json_source_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Handout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=50)),
                ("stage", models.CharField(blank=True, default="", max_length=20)),
                ("grade", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "pdf_file_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handouts",
                        to="courses.course",
                    ),
                ),
                (
                    "creator_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_handouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "handout",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="HandoutQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_no", models.PositiveIntegerField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("question_bank", "question_bank"),
                            ("course", "course"),
                            ("ai", "ai"),
                            ("manual", "manual"),
                        ],
                        default="question_bank",
                        max_length=30,
                    ),
                ),
                ("display_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="handouts.handout",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handout_relations",
                        to="parser.examquestion",
                    ),
                ),
            ],
            options={
                "db_table": "handout_question",
                "ordering": ["sort_no", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("handout", "sort_no"), name="uq_handout_sort_no"
                    ),
                    models.UniqueConstraint(
                        fields=("handout", "question"), name="uq_handout_question"
                    ),
                ],
            },
        ),
    ]
