from django.urls import path
from . import views
from . import wrongbook_matrix_views as matrix_views
from .learning_stats_views import mission_learning_stats

app_name = 'missions'
urlpatterns = [
    path('', views.mission_list, name='mission-list'),
    # Keep both canonical API forms during the existing frontend migration.
    # POST/PUT callers must not depend on APPEND_SLASH redirects.
    path('<uuid:mission_id>', views.mission_detail, name='mission-detail-no-slash'),
    path('<uuid:mission_id>/', views.mission_detail, name='mission-detail'),
    path('<uuid:mission_id>/delete', views.mission_delete, name='mission-delete-no-slash'),
    path('<uuid:mission_id>/delete/', views.mission_delete, name='mission-delete'),
    path('<uuid:mission_id>/levels', views.mission_levels, name='mission-levels-no-slash'),
    path('<uuid:mission_id>/levels/', views.mission_levels, name='mission-levels'),
    path('<uuid:mission_id>/levels/batch', views.mission_levels_batch, name='mission-levels-batch-no-slash'),
    path('<uuid:mission_id>/levels/batch/', views.mission_levels_batch, name='mission-levels-batch'),
    path('<uuid:mission_id>/levels/<uuid:level_id>', views.mission_level_detail, name='mission-level-detail-no-slash'),
    path('<uuid:mission_id>/levels/<uuid:level_id>/', views.mission_level_detail, name='mission-level-detail'),
    path('<uuid:mission_id>/questions', views.mission_questions, name='mission-questions-no-slash'),
    path('<uuid:mission_id>/questions/', views.mission_questions, name='mission-questions'),
    path('<uuid:mission_id>/questions/replace', views.mission_questions, name='mission-questions-replace-no-slash'),
    path('<uuid:mission_id>/questions/replace/', views.mission_questions, name='mission-questions-replace'),
    path('<uuid:mission_id>/kind/<str:kind>', views.mission_set_kind, name='mission-set-kind-no-slash'),
    path('<uuid:mission_id>/kind/<str:kind>/', views.mission_set_kind, name='mission-set-kind'),
    path('<uuid:mission_id>/favorites', views.mission_add_favorites, name='mission-add-favorites-no-slash'),
    path('<uuid:mission_id>/favorites/', views.mission_add_favorites, name='mission-add-favorites'),
    path('<uuid:mission_id>/export-pdf', views.mission_export_pdf, name='mission-export-pdf-no-slash'),
    path('<uuid:mission_id>/export-pdf/', views.mission_export_pdf, name='mission-export-pdf'),
    path('<uuid:mission_id>/grading', views.mission_grading, name='mission-grading-no-slash'),
    path('<uuid:mission_id>/grading/', views.mission_grading, name='mission-grading'),
    path('<uuid:mission_id>/progress', views.mission_progress, name='mission-progress-no-slash'),
    path('<uuid:mission_id>/progress/', views.mission_progress, name='mission-progress'),
    path('<uuid:mission_id>/statistics', views.mission_progress, name='mission-statistics-no-slash'),
    path('<uuid:mission_id>/statistics/', views.mission_progress, name='mission-statistics'),
    path('<uuid:mission_id>/learning-stats', mission_learning_stats, name='mission-learning-stats-no-slash'),
    path('<uuid:mission_id>/learning-stats/', mission_learning_stats, name='mission-learning-stats'),
    path('<uuid:mission_id>/grading/attempts/<uuid:attempt_id>', views.mission_grade_attempt, name='mission-grade-attempt-no-slash'),
    path('<uuid:mission_id>/grading/attempts/<uuid:attempt_id>/', views.mission_grade_attempt, name='mission-grade-attempt'),
    path('<uuid:mission_id>/grading/generate-variant', views.mission_generate_variant, name='mission-generate-variant-no-slash'),
    path('<uuid:mission_id>/grading/generate-variant/', views.mission_generate_variant, name='mission-generate-variant'),
    path('<uuid:mission_id>/publish', views.mission_publish, name='mission-publish-no-slash'),
    path('<uuid:mission_id>/publish/', views.mission_publish, name='mission-publish'),
    path('<uuid:mission_id>/clone', views.mission_clone, name='mission-clone-no-slash'),
    path('<uuid:mission_id>/clone/', views.mission_clone, name='mission-clone'),
    path('<uuid:mission_id>/clone-with-class', views.mission_clone_with_class, name='mission-clone-with-class-no-slash'),
    path('<uuid:mission_id>/clone-with-class/', views.mission_clone_with_class, name='mission-clone-with-class'),
    # Teacher B/C mode guidance
    path('guidance/start/', views.start_teacher_guidance, name='teacher-guidance-start'),
    path('guidance/reply/<str:session_id>/', views.teacher_guidance_reply, name='teacher-guidance-reply'),
    # Phase 4: teacher wrong-book matrix (canonical no-trailing-slash writes).
    path('<uuid:mission_id>/wrongbook-matrix', matrix_views.wrongbook_matrix, name='wrongbook-matrix'),
    path('<uuid:mission_id>/wrongbook-matrix/generate', matrix_views.wrongbook_matrix_generate, name='wrongbook-matrix-generate'),
    path('<uuid:mission_id>/wrongbook-matrix/teacher-generate', matrix_views.teacher_wrongbook_generate, name='teacher-wrongbook-generate'),
    path('<uuid:mission_id>/wrongbook-matrix/history', matrix_views.wrongbook_generation_history, name='wrongbook-matrix-history'),
    path('<uuid:mission_id>/wrongbook-matrix/summary', matrix_views.wrongbook_matrix_summary, name='wrongbook-matrix-summary'),
    path('<uuid:mission_id>/wrongbook-matrix/students/<uuid:student_id>', matrix_views.wrongbook_matrix_student, name='wrongbook-matrix-student'),
    path('<uuid:mission_id>/wrongbook-matrix/refresh-scope', matrix_views.wrongbook_matrix_refresh_scope, name='wrongbook-matrix-refresh-scope'),
    path('<uuid:mission_id>/wrongbook-matrix/close', matrix_views.wrongbook_matrix_close, name='wrongbook-matrix-close'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>', matrix_views.wrongbook_generation_detail_nested, name='wrongbook-generation-detail-nested'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>/retry', matrix_views.wrongbook_generation_retry_nested, name='wrongbook-generation-retry-nested'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>/recommendations', matrix_views.wrongbook_recommendations_nested, name='wrongbook-recommendations-nested'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>/candidate-groups', matrix_views.teacher_wrongbook_candidate_groups_nested, name='teacher-wrongbook-candidate-groups'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>/candidate-groups/confirm', matrix_views.teacher_wrongbook_candidate_groups_confirm_nested, name='teacher-wrongbook-candidate-groups-confirm'),
    path('<uuid:mission_id>/wrongbook-matrix/generation/<uuid:batch_id>/recommendations/confirm', matrix_views.wrongbook_recommendations_confirm_nested, name='wrongbook-recommendations-confirm-nested'),
    path('wrongbook-generation/<uuid:batch_id>', matrix_views.wrongbook_generation_detail, name='wrongbook-generation-detail'),
    path('wrongbook-generation/<uuid:batch_id>/retry', matrix_views.wrongbook_generation_retry, name='wrongbook-generation-retry'),
    path('wrongbook-generation/<uuid:batch_id>/recommendations', matrix_views.wrongbook_recommendations, name='wrongbook-recommendations'),
    path('wrongbook-generation/<uuid:batch_id>/recommendations/confirm', matrix_views.wrongbook_recommendations_confirm, name='wrongbook-recommendations-confirm'),
]
